### ISSUE TITLE
Bug: Sorting order in FE

### ISSUE THREAD

**Issue by michelrossier** [NetConsultAG/netc_ubidb#35]
The sorting order in the frontend is not correct, it should be:
1.	Sort by field “sorting” from the table "tx_netcubidb_domain_model_recht"
2.	Then sort by fields (DE: ubidb_domain_model_bestimmung.artikel_de 
FR: ubidb_domain_model_bestimmung.artikel_fr 
IT: ubidb_domain_model_bestimmung.artikel_it) of each language

The 2. step is correct at the moment, the 1. is not.

Is it possible for you to fix this until the middle of next week? Thank's a lot!

**Comment by jigneshnitsan** [comment]
Hello @michelrossier 
Good Evening!

Thank you for your message.

We have quickly gone through your mentioned points. Please find our comments as below.

**1. Sorting Order**
Comment: Actually, The actual sorting is done on the 2nd step, Which passed through the 1st Step. So obviously it gets overwritten when applied the sorting in 2nd step.

**2. Sort By Fields**
**Status**: Done
**Screenshot**:  http://awesomescreenshot.com/0096co9z56
**Comment**: As you know the records are not managed through default translation. Instead, it managed manually. So for now, We have added a condition for the languages. So, if you introduce any new language then we should adapt this condition.

Let's know your feedback for the same.

Regards.

**Comment by michelrossier** [comment]
Thanks for the information. I've got the feedback from the client that the sorting is not fully correct yet. In the other ticket you've added the content of the field "tx_netcubidb_domain_model_recht" correctly to the output, but now the sorting is not sorting first for that field (as defined in this ticket in "1. Sort by field “sorting” from the table "tx_netcubidb_domain_model_recht") )

Can you make it that way, that first sorting priority is "tx_netcubidb_domain_model_recht" and then the rules in the 2. point in the the initial ticket above:

1. Sort by field “sorting” from the table "tx_netcubidb_domain_model_recht"
2. Then sort by fields (DE: ubidb_domain_model_bestimmung.artikel_de
FR: ubidb_domain_model_bestimmung.artikel_fr
IT: ubidb_domain_model_bestimmung.artikel_it) of each language

Thanks for your efforts!

**Comment by jigneshnitsan** [comment]
Hello @michelrossier 
Good Morning!

Please accept our apologies for the delay. We are too busy at the moment.
Please find our update as below.

**Status**: Done
**Screenshot**: http://prntscr.com/gb1557
**Comment**: We have changed the sorting as per your mentioned point in #1 See this screenshot from code: http://prntscr.com/g9mvvw

**Note**: As I have mentioned in my earlier comment in #Sorting order The current logic is to set order in data the data in two different processes. So either #1 or #2 possible at a time. So for now, we have set as per #1 

Regards.

**Comment by michelrossier** [comment]
Hi @jigneshnitsan 

Thanks for the feedback. I've got the feedback from our programmer:

In the screenshot your provided and in the actual output on the website, the order does not seem to be correct. Let's take fore example the category (entry from "tx_netcubidb_domain_model_recht") "aRTVG": 

![recht](https://user-images.githubusercontent.com/1160557/29715618-6fbcf6e4-89a8-11e7-869b-9daf0823dacb.jpg)

All the entries that are marked yellow should be grouped together when sorted and not spread over the list.

The sorting order is defined here:
![unknown-1](https://user-images.githubusercontent.com/1160557/29715585-49e7243a-89a8-11e7-9850-f9985d3f8982.png)

This defines the order of those categories. So first all entries for "Bundesverfassung" should be listed then "RTVG" etc.

Do you know what I mean?

In regards of combining #1 and #2 lets do it like that: Let's get #1 right as described above. Then we look on our side if we can influence the output order with the order of how we import these fields into the database.

Thanks for your efforts and have a good weekend!

**Comment by jigneshnitsan** [comment]
Hello @michelrossier 
Good Morning!

**Status**: Done
**Screenshot**: http://prntscr.com/ggy7vy
**URL**: http://dev.kommissionv8.netconsult.ch/de/ubi-datenbank/

Regards.

**Comment by michelrossier** [comment]
Hello Jignesh

Thanks for your feedback! The first part of my last comment was addressed perfectly! But the second part was not addressed:

> The sorting order is defined here:
> https://user-images.githubusercontent.com/1160557/29715585-49e7243a-89a8-11e7-9850-f9985d3f8982.png
>
> This defines the order of those categories. So first all entries for "Bundesverfassung" should be listed then "RTVG" etc.

That means the sorting order of these categories is not alphabetically, but according to the order of topics in the screenshot (field "sorting"). And the editor shall be able to change the order there and that must then be reflected on the website.

Can you fix this issue until Wednesday evening?

**Comment by jigneshnitsan** [comment]
Hello @michelrossier 
Good Evening!

I hope you are doing good.

We can't manage both the sorting order at the same time. Either we can go with **Alphabetically** or **Sorting field** wise

If you are still not satisfied then let's connect by tomorrow. I will ask the developer to discuss this thing with you.

Have a nice evening ahead.
Regards.

**Comment by michelrossier** [comment]
Thanks for your feedback. Our programmer was looking into this today, we'll provide feedback as soon as this issue here is solved: https://github.com/NetConsultAG/netc_ubidb/issues/36

Thank you!

**Comment by michelrossier** [comment]
Hi @jigneshnitsan 
Our local developer made the following changes to the file Classes/Domain/Repository/BestimmungRepository.php
 
https://github.com/NetConsultAG/netc_ubidb/commit/61da85b0194d9fd091c684ccffb545e06655e70e

And this made sure that it is sorted by alphabet and by the sorting field order.

So it works as desired. Do you think that is a good solution?

**Comment by jigneshnitsan** [comment]
Hello @michelrossier 
Good Morning!

Thank you for your message. Okay, Let me ask our team to check this.
We will get back to you soon.

Regards.

**Comment by jigneshnitsan** [comment]
Hello @michelrossier 
Good Morning!

Our technical team has reviewed your mentioned changes in the code, It seems that your developer has added the sorting order priority by adding the field next to the main sorting field.
It seems that your main requirement that to Match the Backend Sorting and Front-end Sort order are still not correct. See this screenshots
Back-End list: https://prnt.sc/gr18ay
Order BY Alphabet:  https://prnt.sc/gr14zd
Order BY Sorting: https://prnt.sc/gr15ey
So now, alphabet order not working anymore, 

Can you please check this?

Regards.

**Comment by michelrossier** [comment]
Hi Jignesh

Thanks for your feedback. The explanation I've received is this:

The sorting order now is correct because of the following conditions:
1. The field “sorting” from the table "tx_netcubidb_domain_model_recht" defines the order of the first term in each line, e.g.: "Bundesverfassung", "RTVG" etc.

2. Then the information from the fields like  "ubidb_domain_model_bestimmung.artikel_de" defines inside the results of the "first term" from the order. That makes sure that all texts after "RTVG ..." are alphabetically sorted. E.g:
"RTVG, Art. 4..." and then 
"RTVG, Art. 6..."
etc.

Do you understand how it is meant? The entire line is built together with the information from "tx_netcubidb_domain_model_recht" and also "ubidb_domain_model_bestimmung.artikel_de" and sorted that way.

**Comment by nitsan-technologies** [comment]
Hello @michelrossier 
Good Evening!

Our team has checked your last message. It seems this is been correct in order to what you need in front end. So, we haven't found any issue. 

Have a nice day and a great weekend ahead.
Regards.

**Comment by michelrossier** [comment]
Thanks for your feedback!
